FROM mcr.microsoft.com/dotnet/aspnet:10.0

ARG CERT_PASSWORD

RUN apt-get update && apt-get install -y git

RUN mkdir -p /cert && chown app:app /cert

RUN mkdir -p /photos && chown app:app /photos

RUN openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 365 -nodes -subj "/CN=localhost"
RUN openssl pkcs12 -export -out cert/aspnet.pfx -inkey key.pem -in cert.pem -passout pass:${CERT_PASSWORD}
#è quasi necessaria una password per kestrel, altrimenti si incazza

# necessario per far riscaricare il git sempre
ENTRYPOINT  git clone https://github.com/projectworkits/projectwork-backend.git backend && \
            chmod +x /backend/compiled/projectWork && \
            /backend/compiled/projectWork