FROM nginx:alpine3.23

COPY nginx.conf /etc/nginx/nginx.conf

#COPY ./frontend /frontend

RUN apk update && apk add git

RUN apk update && apk add openssl
RUN mkdir cert
RUN openssl req -x509 -newkey rsa:4096 -keyout cert/priv.key -out cert/cert.crt -sha256 -days 365 -nodes -subj "/C=US/ST=State/L=City/O=Organization/CN=localhost"

ENTRYPOINT  git clone https://github.com/projectworkits/projectwork-frontend.git frontend && \
            chown -R nginx:nginx /frontend && \
            nginx -g "daemon off;"