worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;

    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /cert/cert.crt;
        ssl_certificate_key /cert/priv.key;
        
        ssl_protocols TLSv1.2 TLSv1.3;

        #index index.html;

        error_page 404 /404.html;

        location = /404.html {
            internal;
            root /frontend/projectWork;
        }

        location ~ /\.git {
            deny all;
        }

        location / {
            root /frontend/projectWork;
            index index.html;
            try_files $uri $uri/ $uri.html $uri.htm $uri.js =404;
        }

        location /photos/ {
            alias /frontend/photos/;
        }

        location /swagger/ {
            proxy_pass https://aspnet:3000;
            proxy_ssl_verify off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/ {
            proxy_pass https://aspnet:3000;
            proxy_ssl_verify off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/upload {
            client_max_body_size 20M;

            proxy_read_timeout 60s;
            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;

            proxy_pass https://aspnet:3000;
            proxy_ssl_verify off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 80;
        location / {
            return 301 https://$host$request_uri;
        }
    }
}